controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_weather_city:
    path: '/weather/{city}'
    controller: App\Controller\WeatherController::index
    requirements:
        city: '[a-z]+'